# Generated by Django 5.0.7 on 2024-07-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Product Name')),
                ('price', models.IntegerField()),
                ('pdetail', models.CharField(max_length=300, verbose_name='Product Detail')),
                ('cat', models.IntegerField(choices=[(1, 'vegetables'), (2, 'fruits'), (3, 'meat')], verbose_name='Category')),
            ],
        ),
    ]
