# Generated by Django 5.0.7 on 2024-07-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegitables', '0002_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[(1, 'vegetables'), (2, 'fruits'), (3, 'meat')], max_length=70, verbose_name='Category'),
        ),
    ]
