# Generated by Django 5.0.7 on 2024-07-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegitables', '0006_alter_product_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(verbose_name='Category'),
        ),
    ]
