# Generated by Django 5.0.7 on 2024-07-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegitables', '0009_cart_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amt',
        ),
    ]
