# Generated by Django 5.0.7 on 2024-07-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegitables', '0010_remove_cart_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
